import os
import platform
import subprocess
from collections import OrderedDict, defaultdict

from jinja2 import Environment, FileSystemLoader

from conan import conan_version
from conan.api.output import ConanOutput
from conan.internal.api.detect import detect_api
from conan.internal.cache.home_paths import HomePaths
from conan.tools.env.environment import ProfileEnvironment
from conan.errors import ConanException
from conan.internal.model.conf import ConfDefinition, CORE_CONF_PATTERN
from conan.internal.model.options import Options
from conan.internal.model.profile import Profile
from conan.api.model import RecipeReference
from conan.internal.util.config_parser import TextINIParse
from conan.internal.util.files import mkdir, load_user_encoded


def _unquote(text):
    pass


_default_profile_plugin = """\
# This file was generated by Conan. Remove this comment if you edit this file or Conan
# will destroy your changes.

def profile_plugin(profile):
    settings = profile.settings
    if settings.get("compiler") in ("msvc", "clang") and settings.get("compiler.runtime"):
        if settings.get("compiler.runtime_type") is None:
            runtime = "Debug" if settings.get("build_type") == "Debug" else "Release"
            try:
                settings["compiler.runtime_type"] = runtime
            except ConanException:
                pass
    _check_correct_cppstd(settings)
    _check_correct_cstd(settings)


def _check_correct_cppstd(settings):
    cppstd = settings.get("compiler.cppstd")
    version = settings.get("compiler.version")

    if cppstd and version:
        compiler = settings.get("compiler")
        from conan.tools.build.cppstd import supported_cppstd
        supported = supported_cppstd(None, compiler, version)
        # supported is None when we don't have information about the compiler
        # but an empty list when no flags are supported for this version
        if supported is not None and cppstd not in supported:
            from conan.errors import ConanException
            raise ConanException(f"The provided compiler.cppstd={cppstd} is not supported by {compiler} {version}. "
                                 f"Supported values are: {supported}")


def _check_correct_cstd(settings):
    cstd = settings.get("compiler.cstd")
    version = settings.get("compiler.version")

    if cstd and version:
        compiler = settings.get("compiler")
        from conan.tools.build.cstd import supported_cstd
        supported = supported_cstd(None, compiler, version)
        # supported is None when we don't have information about the compiler
        # but an empty list when no flags are supported for this version
        if supported is not None and cstd not in supported:
            from conan.errors import ConanException
            raise ConanException(f"The provided compiler.cstd={cstd} is not supported by {compiler} {version}. "
                                 f"Supported values are: {supported}")
"""


class ProfileLoader:
    def __init__(self, cache_folder):
        self._home_paths = HomePaths(cache_folder)

    def from_cli_args(self, profiles, settings, options, conf, cwd, context=None):
        """ Return a Profile object, as the result of merging a potentially existing Profile
        file and the args command-line arguments
        """
        pass

    def load_profile(self, profile_name, cwd=None, context=None):
        # TODO: This can be made private, only used in testing now
        pass

    def _load_profile(self, profile_name, cwd, context, root_profile_name):
        """ Will look for "profile_name" in disk if profile_name is absolute path,
        in current folder if path is relative or in the default folder otherwise.
        return: a Profile object
        """
        pass

    def _recurse_load_profile(self, text, profile_path, context, root_profile_name):
        """ Parse and return a Profile object from a text config like representation.
            cwd is needed to be able to load the includes
        """
        pass

    @staticmethod
    def get_profile_path(profiles_path, profile_name, cwd, exists=True):
        pass


# TODO: This class can be removed/simplified now to a function, it reduced to just __init__
class _ProfileParser:

    def __init__(self, text):
        """ divides the text in 3 items:
        - self.includes: List of other profiles to include
        - self.profile_text: the remaining, containing settings, options, env, etc
        """
        self.includes = []
        self.profile_text = ""

        for counter, line in enumerate(text.splitlines()):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("["):
                self.profile_text = "\n".join(text.splitlines()[counter:])
                break
            elif line.startswith("include("):
                include = line.split("include(", 1)[1]
                if not include.endswith(")"):
                    raise ConanException("Invalid include statement")
                include = include[:-1]
                self.includes.append(include)
            else:
                raise ConanException("Error while parsing line %i: '%s'" % (counter, line))


class _ProfileValueParser:
    """ parses a "pure" or "effective" profile, with no includes, no variables,
    as the one in the lockfiles, or once these things have been processed by ProfileParser
    """
    @staticmethod
    def get_profile(profile_text, base_profile=None):
        # Trying to strip comments might be problematic if things contain #
        pass

    @staticmethod
    def _parse_key_value(raw_info):
        pass

    @staticmethod
    def _parse_tool_requires(doc):
        pass

    @staticmethod
    def _parse_settings(doc):
        pass


def _profile_parse_args(settings, options, conf):
    """ return a Profile object result of parsing raw data
    """
    pass


def migrate_profile_plugin(cache_folder):
    pass
