import os
import textwrap

from conan import conan_version
from conan.api.output import ConanOutput
from conan.errors import ConanException, ConanMigrationError
from conan.internal.default_settings import migrate_settings_file
from conan.internal.loader import load_python_file
from conan.internal.model.version import Version
from conan.internal.util.files import load, save

CONAN_GENERATED_COMMENT = "This file was generated by Conan"


def update_file(file_path, new_content):
    """
    Update any file path given with the new content.
    Notice that the file is only updated whether it contains the ``CONAN_GENERATED_COMMENT``.

    :param file_path: ``str`` path to the file.
    :param new_content: ``str`` content to be saved.
    """
    pass


CONAN_VERSION = "version.txt"


class Migrator:

    def __init__(self, conf_path, current_version):
        self.conf_path = conf_path

        self.current_version = current_version
        self.file_version_path = os.path.join(self.conf_path, CONAN_VERSION)

    def migrate(self):
        pass

    def _update_version_file(self):
        pass

    def _load_old_version(self):
        pass

    def _apply_migrations(self, old_version):
        """
        Apply any migration script.

        :param old_version: ``str`` previous Conan version.
        """
        pass

    def _apply_back_migrations(self):
        pass


class ClientMigrator(Migrator):

    def __init__(self, cache_folder, current_version):
        self.cache_folder = cache_folder
        super(ClientMigrator, self).__init__(cache_folder, current_version)

    def _apply_migrations(self, old_version):
        # Migrate the settings if they were the default for that version
        # Time for migrations!
        # Update settings.yml
        pass


def _migrate_default_compatibility(cache_folder):
    # just the back migration
    pass
